config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'health_check', to: 'health_check#status'
  
  resources :sessions, only: [:new, :create]

  resources :airports, only: [:index] do
    resources :lounges, only: [:index]
  end

  resources :lounges, only: [:show] do
    resources :patrons, only: [:index, :create]
    delete 'patronage', :to => 'patrons#destroy'
  end
    
  resources :conversations, only: [:index, :show, :create] do
    resources :messages, only: [:create]
  end

  root 'home#index'
end

app/models/airport.rb
class Airport
  attr_reader :id, :code, :name

  def initialize(id, code, name)
    @id = id
    @code = code
    @name = name
  end
end

app/models/conversation.rb
class Conversation
  attr_reader :id, :sender_id, :recipient_id, :messages
  attr_writer :id

  def initialize(sender_id, recipient_id, messages=[])
    @sender_id = sender_id
    @recipient_id = recipient_id
    @messages = messages

    @id = -1
  end
end

app/models/lounge.rb
class Lounge 
  attr_reader :id, :name, :airport_id, :description
  attr_accessor :number_of_patrons

  def initialize(id, name, airport_id, description = '', number_of_patrons = 0)
    @id = id
    @name = name
    @airport_id = airport_id
    @description = description
    @number_of_patrons = number_of_patrons
  end

  def to_s
    "#{id}) #{name}, #{number_of_patrons} patrons"
  end

end

app/models/message.rb
class Message
  attr_reader :id, :conversation_id, :data, :sender_id, :sender_name

  def initialize(id, conversation_id, data, sender_id, sender_name)
    @id = id
    @conversation_id = conversation_id
    @data = data
    @sender_id = sender_id
    @sender_name = sender_name
  end
end

app/models/patron.rb
class Patron
  attr_reader :id, :name, :hometown, :status

  def initialize(id, name, hometown, status="No status provided...")
    @id = id
    @name = name
    @hometown = hometown 
    @status = status
  end

  def to_s()
    return "(#{id}) #{name} from #{hometown}"
  end

end

app/models/session.rb
class Session
  attr_reader :id, :current_user

  def initialize(id, current_user)
    @id = id
    @current_user = current_user
  end
end

app/models/user.rb
class User
  attr_reader :name, :hometown
  attr_accessor :id, :current_lounge

  def initialize(id, name, hometown, current_lounge=nil)
    @id = id
    @name = name
    @hometown = hometown 
    @current_lounge = current_lounge
  end

  def to_s
    "user_" + @id
  end
end

app/controllers/airports_controller.rb
class AirportsController < ApplicationController
  def index
    @airports = AirportsRepositoryFactory.create_repository.fetch_many()
    @selected_airport = @airports.first
  end
end

app/controllers/application_controller.rb
require 'application_errors'
require 'repositories/sessions/sessions_repository'

class ApplicationController < ActionController::Base
  before_action :check_for_session
  rescue_from NotFoundError, :with => :render_404

  protected
 
  def render_400(error_description)
    render :json => { :error => '400 - Bad Request', :error_description => error_description }, :status => 400
  end
  
  def render_403
    render :file => "#{Rails.root}/public/403.html", :status => 403
  end

  def render_404(e)
    logger.warn("Rendering 404 error! -> " + e.to_s())
    render :file => "#{Rails.root}/public/404.html", :status => 404
  end

  private

  def check_for_session
    session_id = cookies.encrypted[:session_id]
    redirect_to_new_session and return if session_id.nil?
   
    begin
      @session = SessionsRepositoryFactory.create_repository.fetch_by_id(session_id)
    rescue NotFoundError => e
      redirect_to_new_session
    end
  end

  def redirect_to_new_session
      redirect_to :controller => 'sessions', :action => 'new'
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  def index
    @current_user = @session.current_user
    @conversations = ConversationsRepositoryFactory.create_repository.fetch_many(@session.current_user.id)
  end

  def show
    @current_user = @session.current_user
    @conversation = ConversationsRepositoryFactory.create_repository.fetch_by_id(params[:id])
    remote_party_id = @conversation.recipient_id

    if remote_party_id == @current_user.id
      remote_party_id = @conversation.sender_id
    end
      
    @remote_party = UsersRepositoryFactory.create_repository.fetch_user(remote_party_id)
  end

  def create
    patron_id = params[:patron_id]

    begin
      patron = UsersRepositoryFactory.create_repository.fetch_user(patron_id)
    rescue NotFoundError => e
      render_400("No patron found with ID #{patron_id}")
      return
    end

    conversations_repo = ConversationsRepositoryFactory.create_repository

    begin
      conversation = conversations_repo.fetch_by_participant_ids(@session.current_user.id, patron.id)
    rescue NotFoundError => e
      conversation = nil
    end
    
    if conversation.nil?
      # create new conversation by redirecting to show
      conversation = Conversation.new(@session.current_user.id, patron.id)
      conversation = conversations_repo.create!(conversation)
    else
      puts "Found conversation #{conversation.id}, no need to create new one"
    end
      
    redirect_to conversation_path(conversation.id)
  end
end

app/controllers/health_check_controller.rb
class HealthCheckController < ActionController::Base
  def status
    # return 204
    head :no_content
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index()
    @current_user = @session.current_user
  end
end

app/controllers/lounges_controller.rb
class LoungesController < ApplicationController
  def index()
    @lounges = LoungesRepositoryFactory.create_repository.fetch_many(params[:airport_id])
  end

  def show()
    @lounge = LoungesRepositoryFactory.create_repository.fetch_by_id(params[:id])
    @current_user = @session.current_user
  end
end

app/controllers/patrons_controller.rb
class PatronsController < ApplicationController
  def initialize
    super
    @patrons_repo = PatronsRepositoryFactory.create_repository
  end
  
  def index()
    @patrons = @patrons_repo.fetch_many(params[:lounge_id], @session.current_user.id)
    render :partial => 'patrons/index'
  end
  
  def create()
    current_user = @session.current_user
    lounge = LoungesRepositoryFactory.create_repository.fetch_by_id(params[:lounge_id])

    @patrons_repo.leave_lounge(current_user.current_lounge.id, current_user) unless current_user.current_lounge.nil?
    @patrons_repo.check_into_lounge(lounge.id, current_user)
    UsersRepositoryFactory.create_repository.check_into_lounge(lounge, current_user)
    
    redirect_to lounge_path(lounge.id)
  end

  def destroy()
    current_user = @session.current_user
    lounge = LoungesRepositoryFactory.create_repository.fetch_by_id(params[:lounge_id])

    @patrons_repo.leave_lounge(lounge.id, current_user)
    UsersRepositoryFactory.create_repository.check_into_lounge(nil, current_user)

    redirect_to lounge_path(lounge.id)
  end
end

app/controllers/sessions_controller.rb
require 'securerandom'

require 'users/users_repository'

class SessionsController < ApplicationController
  skip_before_action :check_for_session, only: [:new, :create]

  def new()
    # Nothing to do here
  end

  def create()
    user = User.new("-1", params[:name], params[:hometown])
    user = UsersRepositoryFactory.create_repository.create_user(user)
    
    session = Session.new(SecureRandom.uuid, user)
    SessionsRepositoryFactory.create_repository.create(session)
    cookies.encrypted[:session_id] = session.id
    
    redirect_to :controller => 'home', :action => 'index'
  end
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/health_check_helper.rb
module HealthCheckHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lounges_helper.rb
module LoungesHelper
end

app/helpers/patrons_helper.rb
module PatronsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/airports/index.html.erb
<h2>Airport Selection</h2>

<p><%= link_to("Back to Home...", root_path) %></p>

<p>
<%= collection_select(:selected_airport, :id, @airports, :id, :name, {:selected => @selected_airport.id}) %>
</p>

<p><button id="view_lounges_button" name="view_lounges_button" type="button">View lounges</button></p>

<script type="text/javascript">
  $('#view_lounges_button').click(function() {
    window.location.href = '/airports/' + $('#selected_airport_id').val() + '/lounges';
  });
</script>

app/views/conversations/_message.html.erb
<div
    id="message_id_<%= message.id %>" 
    class="<%= if current_user.id == message.sender_id then 'sent-message' else 'received-message' end %>" 
    data-convo-id="<%= message.conversation_id %>" >
    <p><%= message.data %> - <i><%= message.sender_name %></i></p>
</div>

app/views/conversations/index.html.erb
<% @conversations.each do |convo| %>
  <div class="conversation-list-entry">
    <% remote_party = convo.recipient_id == @current_user.id ? convo.sender_id : convo.recipient_id %>
    <p><%= remote_party %> - <%= link_to "View Conversation", conversation_path(convo.id) %></p>
  </div>
<% end %>

app/views/conversations/show.html.erb
<h1>Chat with <%= @remote_party.name %></h1>
<div id="messages">
  <% @conversation.messages.each do |message| %>
    <%= render :partial => "message", :locals => { :message => message, :current_user => @current_user }  %>
  <% end %>
</div>

<%= text_field_tag 'new-message', nil, placeholder: 'Type your message here...' %>
<%= button_tag 'Send', { id: 'send-message-button' } %>

app/views/lounges/index.html.erb
<h1>Lounges Index</h1>

<p><%= link_to("Back to Airports...", airports_path) %></p>

<table>
  <tr>
    <th>Name</th>
  </tr>

  <% @lounges.each do |lounge| %>
  <tr>
    <td><%= link_to(lounge.name, lounge_path(lounge.id)) %></td>
  </tr>
  <% end %>
</table>

app/views/lounges/show.html.erb
<h2><%= @lounge.name %></h2>

<p><%= link_to "Back to Lounges...", airport_lounges_path(@lounge.airport_id) %></p>

<p><%= @lounge.description %></p>
<p>Current Patrons: <%= @lounge.number_of_patrons %></p>

<% if @current_user.current_lounge.nil? %>
  <p><%= link_to "Check in!", lounge_patrons_path(@lounge.id), method: :post %></p>

<% elsif @lounge.id == @current_user.current_lounge.id %>
  <p>You're currently checked into this lounge! Meet some friends!</p>
  <p><%= link_to "Check out", lounge_patronage_path(@lounge.id,), method: :delete %></p>

<% else %>
  <p>You're currently checked into <%= @current_user.current_lounge.name %>. <%= link_to "Click here", lounge_patrons_path(@lounge.id), method: :post %> to leave and check into this lounge.</p>
<% end %>

<script type="text/javascript">
  function getPatrons() {
    $.ajax({
      type: "get",
      url: "<%= lounge_patrons_path(@lounge.id) %>",
      dataType: "html",
      success: function(data) {
        $("#patrons_list").html(data);
      },
      error: function(data) {
        $("#patrons_list").html("<p>Failure fetching patrons!</p>");
      }
    });
  }
</script>

<h3>Patrons</h3>
<a href="#" onclick="getPatrons()">Refresh List</a>
<div id="patrons_list"></div>

<script type="text/javascript">
  $(document).ready(function() {
    getPatrons();
  });
</script>

app/views/patrons/_index.html.erb
<ul>
<% @patrons.each do |patron| %>
  <li>
    <div>
      <p><%= patron.name + " (" + patron.hometown + ")" %></p>
      <p><i><%= patron.status %></i></p>
      <p><%= button_to "Send Message", { :controller => 'conversations', :action => 'create', :patron_id => patron.id }, :method => :post  %></p>
    </div>
  </li>
<% end %>
</ul>

app/views/patrons/index.html.erb
<ul>
<% @patrons.each do |patron| %>
  <li>
    <div>
      <p><%= patron.name + " (" + patron.hometown + ")" %></p>
      <p><i><%= patron.status %></i></p>
      <p><%= button_to "Send Message", { :controller => 'conversations', :action => 'create', :patron_id => patron.id }, :method => :post  %></p>
    </div>
  </li>
<% end %>
</ul>